### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by maoo** [finos/openfin-python-adapter#7]
Hi @LukeSheard !

I see that there haven't been updates on this repo since a long time; is it still used/relevant, or shall we archive it?

Thanks in advance!

**Comment by LukeSheard** [comment]
@maoo I don't work for J.P. Morgan anymore, so it's unlikely I'll ever come back to this.

**Comment by maoo** [comment]
Thanks @LukeSheard ! At this point, unless nobody objects, we will proceed with the archiving of this project by the end of this week.

If anyone wants wants to step up as project maintainer, we'd be happy to unarchive and update permissions accordingly.
